AuthContext and AuthRoutes setup, included useUploadImg, Signup and Login form
ST4R20RD/24Grind-frontend pull request #11
Opened 2022-10-07 17:32 UTC by ST4R20RD

App.tsx
- Signup-Login Route

client.tsx
- Added Request Interceptor to add the token to Authorization Header

Context
- Created Auth Context (Signup, Login, Save/Delete of Token and CurrentUser on LocalStorage) and Context Provider

Components
- Signup
	- Added Signup form
	- Added Input Pattern Validations
	- Added Context Integration
-Login
	- Added Login form
	- Added Input Pattern Validations
	- Added Context Integration
-Layout
	- Check if User is Logged-in in LocalStorage to show Logout Button

2022-10-24 22:19 UTC, GAllen98 commented on src/context/index.tsx
> +    ImgUrl: string
should be lowercase i in img
also general good practice to avoid shortening words (imageUrl would be best)

2022-10-24 22:31 UTC, GAllen98 requested changes

2022-10-24 22:31 UTC, GAllen98 commented on src/context/index.tsx
> +      await client.post("/auth/signup", {
endpoint is `"/v1/users/signup"`

2022-10-24 22:31 UTC, GAllen98 commented on src/context/index.tsx
> +      const response = await client.post("/auth/login", {
endpoint is `"/v1/users/login"`

2022-10-24 22:31 UTC, GAllen98 commented on src/context/index.tsx
> +  const logout = () => {
there's also a logout endpoint: `"/v1/users/logout"`

2022-10-24 22:31 UTC, GAllen98 commented on src/lib/api-hooks.tsx
> +      console.error("AHHHHHHHH!!");
you should probably change this to a more useful error message 😅

2022-10-24 22:31 UTC, GAllen98 commented on src/utils/types.tsx
>    UserImg: string /* || .png/.jpg/... */;
same here as with ImgUrl

2022-10-24 23:18 UTC, SurgeCode commented
you can make endpoints static variables like AUTH_ENDPOINT="/v1/users/signup" if you want and keep them together for easy editing in the future but like this is also good

2022-10-26 17:03 UTC, ST4R20RD commented on src/context/index.tsx
> +    ImgUrl: string
Addressed in COMMIT a502ffecc385ac47cab43b25e14a9a74f030e44e

2022-10-26 17:03 UTC, ST4R20RD commented on src/lib/api-hooks.tsx
> +      console.error("AHHHHHHHH!!");
Addressed in COMMIT a502ffecc385ac47cab43b25e14a9a74f030e44e

2022-10-26 17:03 UTC, ST4R20RD commented on src/utils/types.tsx
>    UserImg: string /* || .png/.jpg/... */;
Addressed in COMMIT a502ffecc385ac47cab43b25e14a9a74f030e44e

2022-10-26 17:03 UTC, ST4R20RD commented on src/context/index.tsx
> +      await client.post("/auth/signup", {
Addressed in COMMIT a502ffecc385ac47cab43b25e14a9a74f030e44e

2022-10-26 17:04 UTC, ST4R20RD commented on src/context/index.tsx
> +  const logout = () => {
Addressed in COMMIT a502ffecc385ac47cab43b25e14a9a74f030e44e

2022-10-26 17:44 UTC, SurgeCode commented on src/context/index.tsx
> +      await client.post("/auth/signup", {
I think you're still missing the /v1

2022-10-26 17:46 UTC, SurgeCode commented on src/context/index.tsx
> +      await client.post("/auth/signup", {
if they dont take forever try let whoever opened a change request to close it

2022-10-26 17:48 UTC, SurgeCode approved these changes

2022-10-30 22:47 UTC, GAllen98 approved these changes

2022-10-30 22:48 UTC, merged