1st iteration of CardComponent, working as a popup
ST4R20RD/24Grind-frontend pull request #2
Opened 2022-08-30 19:11 UTC by ST4R20RD

-Created Card Component:
- [x] Card structure
- [x] Working as a Popup on Navbar Add card button
- [ ] Make every input information editable and saved on db
- [ ] Make types of Card depending on prop "type" (types: New card, Posted card on feed with the ability to comment)

2022-08-31 18:06 UTC, ST4R20RD commented
Header Commit: 
- Changed AddCard Button Position to Header
- Added Logo and Background to Header
![image](https://user-images.githubusercontent.com/93692940/187748764-3534f509-73c6-4dba-afd3-768250a2d4f9.png)

2022-09-04 18:31 UTC, GAllen98 commented on src/components/Card/index.tsx
> +          <div className="flex items-center border border-black rounded-full bg-slate-300 px-2 mx-2">
Create const variables for repeating className values.
That way you'll only have to change one part of the code if you need to.

2022-09-04 18:39 UTC, GAllen98 commented on src/components/Layout/index.tsx
>    const isMobile = window.innerWidth <= 425;
Avoid magic variables.
Turn 425 into a constant

2022-09-09 18:12 UTC, GAllen98 requested changes

2022-09-09 18:12 UTC, GAllen98 commented on src/components/Card/index.tsx
> +          <div className="flex items-center border border-black rounded-full bg-slate-300 px-2 mx-2">
Create const variables for repeating className values.
That way you'll only have to change one part of the code if you need to.

2022-09-09 18:12 UTC, GAllen98 commented on src/components/Layout/index.tsx
>    const isMobile = window.innerWidth <= 425;
Avoid magic variables.
Turn 425 into a constant

2022-09-09 18:48 UTC, GAllen98 approved these changes

2022-09-09 18:51 UTC, ST4R20RD commented on src/components/Layout/index.tsx
>    const isMobile = window.innerWidth <= 425;
The layout will be changed in another branch to always display the app in mobile format and then after the MVP, the layout will show desktop version also, as for the mean time the purpose of this MVP is for proof of concept for a mobile app.

2022-09-09 18:52 UTC, merged

2022-09-09 18:55 UTC, ST4R20RD commented on src/components/Layout/index.tsx
>    const isMobile = window.innerWidth <= 425;
But in case that this system of using window.innerWidth would togo to the final product, i completely agree with the "magic variable" advice that for sure I'll take in consideration next time I do something similar.