Re-design CardComponent
ST4R20RD/24Grind-frontend pull request #8
Opened 2022-09-14 21:30 UTC by ST4R20RD

Complete Re-Design of Card Component now looking like this: 
![image](https://user-images.githubusercontent.com/93692940/190266072-8404eb5a-a422-4b87-a865-194882d65b26.png)

2022-09-19 18:27 UTC, GAllen98 approved these changes

2022-09-19 18:39 UTC, GAllen98 requested changes
CardForm incomplete

2022-09-24 14:40 UTC, GAllen98 commented on src/components/CardForm/index.tsx
> +const mockLocations = [
acho q os locations n vao precisar de id

2022-09-24 14:42 UTC, GAllen98 approved these changes

2022-09-24 14:42 UTC, GAllen98 commented on src/components/CardForm/index.tsx
> +const mockCategories = [
same here, as categories podem ser só strings

2022-09-25 19:33 UTC, SurgeCode commented on src/components/CardForm/index.tsx
> +
Remove logging from final pr

2022-09-25 19:33 UTC, SurgeCode commented on src/components/CardForm/FormBtnDrop.tsx
> +}
possibly move types into separate file inside the folder

2022-09-25 19:41 UTC, SurgeCode commented on src/components/CardForm/index.tsx
> +
any

2022-09-29 20:45 UTC, ST4R20RD commented
Description of Commit AB#{ce8fd83e2549e2cf72cce4adaec3a34e40098c6c} Changes: 
App index
- Created Route Page => Create

Pages
- Added Create Page

CardForm
- Adressed the "any" types to correct types
- Removed anything Groups for POC
- Prepared Button before introduction of "Add Image" feature

Layout
- Handled hidden of Create button when on Create Page

FormButton
- Change Options list from Dropdown to Popup
- Added the ability to Search Users from Popup List
- Added the ability to remove individual selected Users

Modal
- Added the ability to close when click outside

api-hooks
- Added useGetSearchUsers

2022-09-29 20:46 UTC, ST4R20RD commented on src/components/CardForm/index.tsx
> +
Adressed https://github.com/ST4R20RD/24Grind-frontend/pull/8#issuecomment-1262795747

2022-09-29 20:49 UTC, ST4R20RD commented on src/components/CardForm/index.tsx
> +const mockCategories = [
The problem is that I need the lists to be in the format { id: number, name: string } to work on the FormBtnDrop component. For the MVP I will try to work on a better solution

2022-09-29 20:50 UTC, ST4R20RD commented on src/components/CardForm/index.tsx
> +const mockLocations = [
Adressed https://github.com/ST4R20RD/24Grind-frontend/pull/8#issuecomment-1262795747

2022-10-11 19:11 UTC, merged